version: '3.9'

services:
  agent:
    build:
      context: ./
      dockerfile: ./build/Dockerfile
    restart: unless-stopped
    ports:
      - "2552:2552"
    networks:
      - expression-backend-2_network
networks:
  expression-backend-2_network:
    external: true
