version: '3.9'

services:
  agent:
    build:
      context: ./
      dockerfile: ./build/Dockerfile
    restart: unless-stopped
    ports:
      - "2552:2552"
    networks:
      - network
networks:
  network:
    driver: bridge