version: '3.9'

services:
  app:
    build:
      context: ./
      dockerfile: ./build/Dockerfile
    restart: unless-stopped
    networks:
      - network
#networks:
#  network:
#    name: expression-network
#    driver: bridge
#    external: true